#!/usr/bin/env bash

export COPASI_PACKAGE=Darwin
export VARIABLES="$HOME/build-system/variables/darwin"
export COPASI_READLINK=greadlink
export PATH="$HOME/build-system/bin:/usr/local/bin::$PATH"
export BUILD_ROOT="$(dirname "$(dirname "$(${COPASI_READLINK:-readlink} -f "$BASH_SOURCE")")")"

PS1="[\\u@${COPASI_PACKAGE} \\W]\\\$ "
