#!/usr/bin/env bash

export COPASI_PACKAGE=Darwin-arm
export VARIABLES="$HOME/build-system-arm/variables/darwin-arm"
export COPASI_READLINK=greadlink
export PATH="$HOME/build-system-arm/bin:/opt/homebrew/bin:$PATH"
export BUILD_ROOT="$(dirname "$(dirname "$(${COPASI_READLINK:-readlink} -f "${(%):-%N}")")")"

PS1="[\\u@${COPASI_PACKAGE} \\W]\\\$ "
