#!/usr/bin/env bash

if [ -z ${BUILD_SYSTEM_HOME+x} ];
then
    export BUILD_SYSTEM_HOME=$HOME
fi
export COPASI_PACKAGE=Darwin
export VARIABLES="$BUILD_SYSTEM_HOME/build-system/variables/darwin"
export COPASI_READLINK=greadlink
export PATH="$BUILD_SYSTEM_HOME/build-system/bin:$PATH"
PS1="[\\u@${COPASI_PACKAGE} \\W]\\\$ "
