#!/usr/bin/env bash

if [ -z ${BUILD_SYSTEM_HOME+x} ];
then
    export BUILD_SYSTEM_HOME=$HOME
fi
export COPASI_PACKAGE=Darwin-arm
export VARIABLES="$BUILD_SYSTEM_HOME/build-system-arm/variables/darwin-arm"
export COPASI_READLINK=greadlink
export PATH="$BUILD_SYSTEM_HOME/build-system-arm/bin:$PATH"

if [ -n "$ZSH_VERSION" ]; then
PS1="[%n@${COPASI_PACKAGE} %~] $ "
else
PS1="[\\u@${COPASI_PACKAGE} \\W]\\\$ "
fi
