#!/usr/bin/env bash

export COPASI_PACKAGE=Darwin-arm
export HOME_BUILD_SYSTEM=${HOME_BUILD_SYSTEM:=$HOME}
export VARIABLES="$HOME_BUILD_SYSTEM/build-system-arm/variables/darwin-arm"
export COPASI_READLINK=greadlink
export PATH="$HOME_BUILD_SYSTEM/build-system-arm/bin:/opt/homebrew/bin:$PATH"
export BUILD_ROOT="$(dirname "$(dirname "$(${COPASI_READLINK:-readlink} -f "${(%):-%N}")")")"

PS1="[\\u@${COPASI_PACKAGE} \\W]\\\$ "
