#!/usr/bin/env bash

if [ -z ${BUILD_SYSTEM_HOME+x} ];
then
    export BUILD_SYSTEM_HOME=$HOME
fi

alias arm="env /usr/bin/arch -arm64 /opt/homebrew/bin/bash --init-file $BUILD_SYSTEM_HOME/build-system-arm/profile/darwin-arm"
alias intel="env /usr/bin/arch -x86_64 /usr/local/bin/bash --init-file $BUILD_SYSTEM_HOME/build-system-intel/profile/darwin-intel"
