#!/usr/bin/env bash

export HOME_BUILD_SYSTEM=${HOME_BUILD_SYSTEM:=$HOME}
alias arm="env /usr/bin/arch -arm64 /opt/homebrew/bin/bash --init-file $HOME_BUILD_SYSTEM/build-system-arm/profile/darwin-arm"
alias intel="env /usr/bin/arch -x86_64 /usr/local/bin/bash --init-file $HOME_BUILD_SYSTEM/build-system-intel/profile/darwin-intel"
