#!/usr/bin/env bash

export COPASI_PACKAGE=Darwin-intel
export HOME_BUILD_SYSTEM=${HOME_BUILD_SYSTEM:=$HOME}
export VARIABLES="$HOME_BUILD_SYSTEM/build-system-intel/variables/darwin-intel"
export COPASI_READLINK=greadlink
export PATH="$HOME_BUILD_SYSTEM/build-system-intel/bin:/usr/local/bin:$PATH"
export BUILD_ROOT="$(dirname "$(dirname "$(${COPASI_READLINK:-readlink} -f "${(%):-%N}")")")"

export QTDIR=/Users/copasi/6.7.0/macos

if [ -n "$ZSH_VERSION" ]; then
PS1="[%n@${COPASI_PACKAGE} %~] $ "
else
PS1="[\\u@${COPASI_PACKAGE} \\W]\\\$ "
fi
