#!/usr/bin/env bash

export HOME_BUILD_SYSTEM=${HOME_BUILD_SYSTEM:=$HOME}
export VARIABLES=${VARIABLES:="$HOME_BUILD_SYSTEM/build-system/variables/linux-64"}
export COPASI_PACKAGE="Linux-64bit"
export BUILD_ROOT="$(dirname "$(dirname "$(${COPASI_READLINK:-readlink} -f "$BASH_SOURCE")")")"
export PATH="${BUILD_ROOT}/bin:$PATH"
