#!/usr/bin/env bash

if [ -z ${BUILD_SYSTEM_HOME+x} ];
then
    export BUILD_SYSTEM_HOME=$HOME
fi
export VARIABLES="$BUILD_SYSTEM_HOME/build-system/variables/linux-64"
export COPASI_PACKAGE="Linux-64bit"
export PATH="$BUILD_SYSTEM_HOME/build-system/bin:$PATH"
