#!/usr/bin/env bash

export HOME_BUILD_SYSTEM=${HOME_BUILD_SYSTEM:=$HOME}
export BUILD_ROOT="$(dirname "$(dirname "$(${COPASI_READLINK:-readlink} -f "$BASH_SOURCE")")")"
export PATH="${BUILD_ROOT}/bin:$/usr/bin:/usr/local/bin:PATH"
PS1="[\\u@windows \\W]\\\$ "
