# This is a basic workflow to help you get started with Actions

name: macOS Installer build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      COPASI_REPOSITORY:
        description: "COPASI repository"
        required: true
        default: https://github.com/copasi/COPASI.git

      COPASI_DEPENDENCIES_REPOSITORY:
        description: "COPASI dependencies repository"
        required: true
        default: https://github.com/copasi/copasi-dependencies.git

      COPASI_DEPENDENCIES_CLONE_OPTS:
        description: "COPASI dependencies clone options"
        required: false
        default: ""
      COPASI_BRANCH:
        description: "COPASI branch"
        required: false
        default: release/Version-4.47

      COPASI_COMMENT:
        description: "COPASI comment"
        required: false
        default: stable
      ARTIFACT_COMMENT:
        description: "Artifact comment"
        required: false
        default: ""

      QT_VERSION_NUMBER:
        description: "QT version number"
        required: true
        default: 6.10.0

      ENABLE_OMP:
        description: "Enable OpenMP (sets ENABLE_OMP env to ON or OFF for CMake)"
        required: false
        type: boolean
        default: true

  # run this task every week at 2am
  schedule:
    - cron: '0 2 * * 0'

env:
  COPASI_REPOSITORY: ${{ inputs.COPASI_REPOSITORY || 'https://github.com/copasi/COPASI.git' }}
  COPASI_DEPENDENCIES_REPOSITORY: ${{ inputs.COPASI_DEPENDENCIES_REPOSITORY || 'https://github.com/copasi/copasi-dependencies.git' }}
  COPASI_DEPENDENCIES_CLONE_OPTS: ${{ inputs.COPASI_DEPENDENCIES_CLONE_OPTS || '' }}
  ARTIFACT_COMMENT: ${{ inputs.ARTIFACT_COMMENT || '' }}
  QT_VERSION_NUMBER: ${{ inputs.QT_VERSION_NUMBER || '6.10.0' }}
  COPASI_BRANCH: ${{ inputs.COPASI_BRANCH || 'release/Version-4.47' }}
  COPASI_COMMENT: ${{ inputs.COPASI_COMMENT || 'stable' }}

      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    environment: deploy

    name: ${{ matrix.architectures }}

    strategy:
      fail-fast: false
      matrix:
        architectures: [arm64, x86_64]

    # setup environment variables
    env:
      MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
      MACOS_KEYCHAIN_PWD: ${{ secrets.MACOS_KEYCHAIN_PWD }}
      MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
      MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
      MACOS_NOTARIZATION_PWD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
      ARCHITECTURES: ${{ matrix.architectures }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11' 
      
      - name: install dependencies
        shell: bash
        run: |
          brew install wget astyle openjdk gawk coreutils bash 
          brew install --cask mono-mdk

          if [ "${{ matrix.architectures }}" = "arm64" ]; then
            brew install libomp
            # set libomp prefix environment variable and add to GITHUB_ENV
            export LIBOMP_PREFIX=$(brew --prefix libomp)
            echo "LIBOMP_PREFIX=$LIBOMP_PREFIX" >> $GITHUB_ENV
          else
            if [ ! -x /usr/local/bin/brew ]; then
              NONINTERACTIVE=1 arch -x86_64 /bin/bash -c \
                "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            fi
            arch -x86_64 /usr/local/bin/brew install libomp
            # set libomp prefix environment variable and add to GITHUB_ENV
            export LIBOMP_PREFIX=$(arch -x86_64 /usr/local/bin/brew  --prefix libomp)
            echo "LIBOMP_PREFIX=$LIBOMP_PREFIX" >> $GITHUB_ENV
          fi

      - name: create virtual environment
        shell: bash
        run: |
          python3 -m venv env-build
          source ./env-build/bin/activate
          pip install aqtinstall swig cmake ninja 
          aqt install-qt mac desktop $QT_VERSION_NUMBER clang_64 -m qt5compat qtcharts qtdatavis3d          
          ls $PWD/${QT_VERSION_NUMBER}/macos/bin

      - name: checkout build system
        run: |
          git clone https://github.com/copasi/build-system
          
      - name: initialize build system, compile dependencies
        shell: bash
        run: |
          # print bash version
          bash --version
          # print bash location
          which bash
          
          export PATH=$PWD/env-build/bin:$PATH
          export HOME_BUILD_SYSTEM=$PWD
          source ./env-build/bin/activate
          source build-system/profile/darwin-universal
          export Qt6_DIR=$PWD/${QT_VERSION_NUMBER}/macos
          export PATH=$PWD/${QT_VERSION_NUMBER}/macos/bin/:$PATH
          export SELECT_QT=Qt6         

          # emerge 
          emerge 

          # build dependencies, ignore exit code
          install-dependencies || true

      - name: build release
        shell: bash
        run: |
          # print bash version
          bash --version
          # print bash location
          which bash
          
          export PATH=$PWD/env-build/bin:$PATH
          export HOME_BUILD_SYSTEM=$PWD
          source ./env-build/bin/activate
          source build-system/profile/darwin-universal
          export Qt6_DIR=$PWD/${QT_VERSION_NUMBER}/macos
          export PATH=$PWD/${QT_VERSION_NUMBER}/macos/bin/:$PATH
          export SELECT_QT=Qt6

          if [ "${{ matrix.architectures }}" = "arm64" ]; then
            export COPASI_PACKAGE=Darwin-arm
          else
            export COPASI_PACKAGE=Darwin-intel
          fi

          echo "COPASI_PACKAGE=${COPASI_PACKAGE}" >> $GITHUB_ENV

          if [ ${{ inputs.ENABLE_OMP }} ]; then
            echo Enable OpenMP support
            export ENABLE_OMP=ON
          fi
  
          # build release
          release --branch ${COPASI_BRANCH} --comment ${COPASI_COMMENT} --noscp

          # fail workflow if binary is not found
          app_path=(build-system/packages/setup.release/COPASI-*-Darwin/COPASI/CopasiUI.app)

          if [ ! -d "${app_path[0]}" ]; then
            echo "COPASI UI binary not found"
            exit 1
          fi

          export COPASI_SOURCES=${BUILD_ROOT}/git/COPASI.release
          source ${BUILD_ROOT}/bin/functions
          version

          echo "COPASI_VERSION_SOURCE=$sourceVersion" >> $GITHUB_ENV
          echo "COPASI_VERSION_TARGET=$targetVersion" >> $GITHUB_ENV

          # remove binding folders as we have the tar.gz by now
          rm -rf build-system/packages/setup.release/*Bindings*Darwin


      - name: create keychain, sign executables create DMG
        shell: bash
        run: |
          echo -n "$MACOS_CERTIFICATE" | base64 --decode -o certificate.p12
          security create-keychain -p "$MACOS_KEYCHAIN_PWD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$MACOS_KEYCHAIN_PWD" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_KEYCHAIN_PWD" build.keychain
          security list-keychain -d user -s build.keychain
          security find-identity -v -p codesigning

          # now sign the executables
          export HOME_BUILD_SYSTEM=$PWD
          pushd build-system/packages/setup.release/COPASI-${COPASI_VERSION_SOURCE}-Darwin/COPASI/
          cp $HOME_BUILD_SYSTEM/build-system/src/entitlements.plist .
          /usr/bin/codesign --force --deep -s "$MACOS_CERTIFICATE_NAME" --options runtime --entitlements ./entitlements.plist CopasiUI.app -v
          /usr/bin/codesign --force --timestamp -s "$MACOS_CERTIFICATE_NAME" --options runtime --entitlements ./entitlements.plist CopasiSE -v
          /usr/bin/codesign -vvvv CopasiUI.app

          rm entitlements.plist
          popd
          
          pushd build-system/packages/setup.release/COPASI-${COPASI_VERSION_SOURCE}-Darwin/COPASI/

          # store credentials to avoid UI prompts for passwords
          xcrun notarytool store-credentials "notarytool-profile" --apple-id "$MACOS_NOTARIZATION_APPLE_ID" --team-id "$MACOS_NOTARIZATION_TEAM_ID" --password "$MACOS_NOTARIZATION_PWD"

          # zip GUI app
          ditto -c -k --keepParent "CopasiUI.app" "notarization_gui.zip"
          # submit to be notarized
          xcrun notarytool submit "notarization_gui.zip" --keychain-profile "notarytool-profile" --wait
          # attach resulting staple to app for offline validation
          xcrun stapler staple "CopasiUI.app"
          # repeat for CLI - but note that although we can notarize a command line binary we can't staple it
          ditto -c -k --keepParent "CopasiSE" "notarization_cli.zip"
          xcrun notarytool submit "notarization_cli.zip" --keychain-profile "notarytool-profile" --wait

          rm notarization_*.zip
          popd

          pushd build-system/packages/setup.release/


          # create the DMG
          hdiutil create -verbose -volname COPASI-${COPASI_VERSION_TARGET}-Darwin -fs HFS+ -srcfolder ./COPASI-${COPASI_VERSION_SOURCE}-Darwin/  -ov -format UDZO COPASI-${COPASI_VERSION_SOURCE}-${COPASI_PACKAGE}.dmg
          sudo /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_NAME" COPASI-${COPASI_VERSION_SOURCE}-${COPASI_PACKAGE}.dmg -v

          # notarize & staple the dmg
          ditto -c -k --keepParent "COPASI-${COPASI_VERSION_SOURCE}-${COPASI_PACKAGE}.dmg" "notarization_gui_dmg.zip"
          xcrun notarytool submit "notarization_gui_dmg.zip" --keychain-profile "notarytool-profile" --wait
          xcrun stapler staple "COPASI-${COPASI_VERSION_SOURCE}-${COPASI_PACKAGE}.dmg"

          # prepare scp deployment
          cp "COPASI-${COPASI_VERSION_SOURCE}-${COPASI_PACKAGE}.dmg" $HOME_BUILD_SYSTEM/build-system/upload/"COPASI-${COPASI_VERSION_TARGET}-${COPASI_PACKAGE}.dmg"

          rm notarization_gui_dmg.zip

          popd


      - name: remove keychain
        run: |
          security delete-keychain build.keychain

      - name: create release archive
        shell: bash
        run: |
          # zip the COPASI-*-Darwin folder
          pushd build-system/packages/setup.release/
          zip -r -q -y COPASI-$COPASI_VERSION_TARGET-${COPASI_PACKAGE}.zip ./COPASI-${COPASI_VERSION_SOURCE}-Darwin/
          popd

      - uses: actions/upload-artifact@v7
        with:
          name: macOS-${{ matrix.architectures }}${{ env.ARTIFACT_COMMENT }}
          path: |
            build-system/packages/setup.release/*.zip
            build-system/packages/setup.release/*.tar.gz
          retention-days: 7
          if-no-files-found: error
      
      - uses: actions/upload-artifact@v7
        with:
          name: macOS DMG ${{ matrix.architectures }}${{ env.ARTIFACT_COMMENT }}
          path: |
            build-system/packages/setup.release/*.dmg
          retention-days: 7
          if-no-files-found: error


      - name: determine files to deploy
        shell: bash
        run: |
          find build-system/upload/ -type f > FILES_TO_DEPLOY
          echo "FILES_TO_DEPLOY=$(paste -sd ',' FILES_TO_DEPLOY)"  >> $GITHUB_ENV
          rm FILES_TO_DEPLOY 

          
      - name: deploy files
        uses: shoops/scp-action@v-1.0.1
        with:
          source: ${{ env.FILES_TO_DEPLOY }}
          target: build-system/upload/stage
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.PRIVATE_KEY }}      
          port: 22
          strip_components: 2